server:
  port: 8102
spring:
  application:
    name: ms-bank-account-balance-service
 # config:
  #  import: optional:configserver:http://ms-bank-config-server:8888
  data: 
    mongodb:
     host: localhost
     port: 27017
     database: Bank 
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

kafka:
  topic:
    bank:
      account-balance:
        create:
          name: bank-account-balance-create